# Open applications on specific workspaces
assign [class="firefoxdeveloperedition"] $ws2
assign [class="Google-chrome"] $ws2
assign [class="Brave-browser"] $ws2
assign [class="jetbrains-phpstorm"] $ws1
assign [class="Code"] $ws1
assign [class="Insomnia"] $ws3
assign [class="jetbrains-datagrip"] $ws4
assign [class="tinkerwell"] $ws4
assign [class="vlc"] $ws7 
assign [class="GitKraken"] $ws8
assign [class="Slack"] $ws9
assign [class="discord"] $ws9 
assign [class="cryptowatch_desktop"] $ws10

# Open specific applications in floating mode
# Manjaro Defaults
for_window [title="alsamixer"] floating enable border pixel 1
for_window [class="calamares"] floating enable border normal
for_window [class="Clipgrab"] floating enable
for_window [title="File Transfer*"] floating enable
for_window [class="fpakman"] floating enable
for_window [class="Galculator"] floating enable border pixel 1
for_window [class="GParted"] floating enable border normal
for_window [title="i3_help"] floating enable sticky enable border normal
for_window [class="Lightdm-settings"] floating enable
for_window [class="Lxappearance"] floating enable sticky enable border normal
for_window [class="Manjaro-hello"] floating enable
for_window [class="Manjaro Settings Manager"] floating enable border normal
for_window [title="MuseScore: Play Panel"] floating enable
for_window [class="Nitrogen"] floating enable sticky enable border normal
for_window [class="Oblogout"] fullscreen enable
for_window [class="octopi"] floating enable
for_window [title="About Pale Moon"] floating enable
for_window [class="Pamac-manager"] floating enable
for_window [class="Pavucontrol"] floating enable
for_window [class="qt5ct"] floating enable sticky enable border normal
for_window [class="Qtconfig-qt4"] floating enable sticky enable border normal
for_window [class="Simple-scan"] floating enable border normal
for_window [class="(?i)System-config-printer.py"] floating enable border normal
for_window [class="Skype"] floating enable border normal
for_window [class="Timeset-gui"] floating enable border normal
for_window [class="(?i)virtualbox"] floating enable border normal
for_window [class="Xfburn"] floating enable

# Custom Window Overrides
for_window [title="win0"] floating enable # PHPStorm & Datagrip
for_window [class="code-oss"] layout tabbed
for_window [class="^jetbrains-.+"][window_type=dialog] focus
for_window [class="^jetbrains-.+"] layout tabbed
for_window [class="^datagrip-.+"] layout tabbed
for_window [class="GitKraken"] layout tabbed